# Rule description: https://github.com/realm/SwiftLint/blob/master/Rules.md
disabled_rules: # rule identifiers to exclude from running
  - line_length
  - trailing_whitespace
  - force_try
  - force_cast
  - shorthand_operator
  - unused_closure_parameter
  - discarded_notification_center_observer
  - weak_delegate
  - identifier_name
opt_in_rules: # some rules are only opt-in
  - empty_count
  # Find all the available rules by running:
  # swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
  - SwiftBeauty
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length:
  warning: 250
  error: 500
# they can set both implicitly with an array
type_body_length:
  - 300 # warning
  - 600 # error
# or they can set both explicitly
file_length:
  warning: 400
  error: 800
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
custom_rules:
  more_thane_one_space:
    include: "*.swift"
    name: "Redundant space" 
    regex: "([a-z,A-Z] \\s+)"
    message: "More than one space between keywords" 
    match_kinds: keyword 
    severity: warning
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
